env:
  browser: true
  es6: true
globals:
  Atomics: readonly
  SharedArrayBuffer: readonly
plugins:
  - react
extends:
  - plugin:react/recommended
  - standard
parserOptions:
  ecmaFeatures:
    jsx: true
  ecmaVersion: 2018
  sourceType: module
settings:
  react:
    version: detect
rules:
  space-before-function-paren:
    - error
    - never
